# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: So Little Time
email: elijah.dunn@ku.edu
description: >
  This needs updating...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ekdunn.github.io/" # the base hostname & protocol for your site
github_username:  ekdunn
timezone: America/Chicago
source: /home/edunn/.jekyll/
destination: /home/edunn/web/
exclude: _private/

# Build settings
markdown: kramdown
