title: Newton's Flaming Laser Sword
short_title: FlamingLasrSwrd
#email: elijah.k.dunn+fls@gmail.com
description: >
  An unfinished collection.
baseurl: ""
url: "http://flaminglasersword.com"
#github_username:  flaminglasrswrd
date_format: "%b %-d, %Y"
header_pages:
 - about.md
 - log.md

# Build settings
#markdown: kramdown
theme: jekyll-theme-midnight
#plugins_dir:
#  - jekyll-feed
#  - github-pages
#  - jekyll-paginate
#  - jekyll-last-modified-at
#  - jekyll-pandoc-multiple-formats
exclude:
  - Gemfile
  - Gemfile.lock
  - _private
permalink: pretty
paginate: 7
#destination: ../flaminglasersword/

# Conversion
excerpt_separator: "<!--more-->"


# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-121123907-1
google_tag_manager:
# Bing services
bing_verification:
# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: true
extended_fonts: false
enable_anchorjs: false

# Preview image for social media aka og:image and twitter:image
post_preview_image: false
# Facebook Page integration
# (for instant articles and other stuff)
fb_page: https://www.facebook.com/FlamingLasrSwrd/
fb_page_id: FlamingLasrSwrd

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# txtpen post comments
# (leave blank to disable txtpen)
txtpen_sitename:

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments: true
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: flaminglasrswrd
reddit_username: flaminglasrswrd
wikipedia_username: flaminglasrswrd
instructables_username: FlamingLasrSwrd
stackoverflow_id: 9530723
twitter_username: flaminglasrswrd
instagram_username: flaminglasrswrd
bitbucket_username:
skype_username:
steam_nickname: ekdunn
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url: 32Raj9qa4tZeXEK1aq9wonr8t9GHZYqy7t
paypal_url: paypal.me/ekdunn
flattr_button:
telegram_username:
vk_id:


# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    created:        'Created'
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    updated: 'Updated'
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

# Pandoc
markdown: pandoc
pandoc:
    skip: true
#    bundle_permalink: 'bundle/:output_ext/:slug.:output_ext'
    papersize: 'a5paper'
    sheetsize: 'a4paper'
    imposition: true
    binder: true
    covers_dir: assets/covers
    signature: 20
    flags: '--smart'
    site_flags: '--toc --bibliography=_data/library.bib --metadata link-citations=true'
    outputs:
      latex:
      pdf: '--latex-engine=xelatex'
      epub: '--epub-chapter-level=2'
